# Generated by Django 5.1.2 on 2024-11-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_car_owner_alter_car_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время последнего обновления записи'),
        ),
    ]
