# Generated by Django 5.1.2 on 2024-11-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_car_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='updated_at',
            field=models.DateTimeField(blank=True, verbose_name='Дата и время последнего обновления записи'),
        ),
    ]
